### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by kazushi07** [kazushi07/chat-space#13]
#IPアドレス
18.181.39.100

**Comment by mutorisa** [comment]
堅田さん、ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。

**Comment by kazushi07** [comment]
ご確認いただきありがとうございます！
今後の質問につきましてもかしこまりました！！
